{
  "0": "Tempolimit (20 km/h)",
  "1": "Tempolimit (30 km/h)",
  "2": "Tempolimit (50 km/h)",
  "3": "Tempolimit (60 km/h)",
  "4": "Tempolimit (70 km/h)",
  "5": "Tempolimit (80 km/h)",
  "6": "Ende von Tempolimit (80 km/h)",
  "7": "Tempolimit (100 km/h)",
  "8": "Tempolimit (120 km/h)",
  "9": "Überholverbot",
  "10": "Überholverbot für Fahrzeuge > 3,5t",
  "11": "Vorfahrt an nächster Kreuzung",
  "12": "Vorfahrtstraße",
  "13": "Vorfahrt gewähren",
  "14": "Stop",
  "15": "Verbot für Fahrzeuge aller Art",
  "16": "Verbot für Fahrzeuge > 3,5t",
  "17": "Einfahrt verboten",
  "18": "Allgemeine Gefahr",
  "19": "Kurve nach links",
  "20": "Kurve nach rechts",
  "21": "Doppelkurve",
  "22": "Unebene Fahrbahn",
  "23": "Schleudergefahr",
  "24": "Fahrbahnverengung rechts",
  "25": "Straßenarbeiten",
  "26": "Ampel",
  "27": "Fußgänger",
  "28": "Kinder",
  "29": "Radfahrer",
  "30": "Schnee- oder Eisglätte",
  "31": "Wildwechsel",
  "32": "Ende aller Streckenverbote",
  "33": "Rechts abbiegen",
  "34": "Links abbiegen",
  "35": "Geradeaus",
  "36": "Geradeaus oder rechts",
  "37": "Geradeaus oder links",
  "38": "Rechts halten",
  "39": "Links halten",
  "40": "Kreisverkehr",
  "41": "Ende Überholverbot",
  "42": "Ende Überholverbot für Fahrzeuge > 3,5t"
}
